### ISSUE TITLE
Display entry link asset in Sinatra .erb

### ISSUE THREAD

**Issue by whosdustin** [contentful/contentful_sinatra_tutorial#1]
Trying to display images from a single entry in Contentful. How do I display this. Right now this is what I am trying to attempt:

```
<% product.images.each do |image| %>
  <img src="<%= image.image_url %>" >
<% end %>
```

I continuously am getting an error: **undefined method 'image_url'**

**Comment by dlitvakb** [comment]
Hey @whosdustin,

Could you send me the contents of your `image` object in there?

**Comment by dlitvakb** [comment]
Also, if you're using the Product Catalogue template from the Contentful Web App, your `images` field, should be called `image` (in singular, as that's the field id)

**Comment by whosdustin** [comment]
I mimicked the product catalog but changed a few things for personal preference.
```
{
      "name": "Images",
      "id": "images",
      "type": "Array",
      "items": {
        "type": "Link",
        "linkType": "Asset",
        "validations": []
      },
      "validations": []
    },
```

**Comment by dlitvakb** [comment]
Cool, what's the content of `image` inside that execution block?

**Comment by whosdustin** [comment]
Just `# #` since there are 2 images associated with it.

`<%= image.type %>` displays `Link Link`  Also, `image.id` is the only other method recognized.

**Comment by dlitvakb** [comment]
Looks like the link is not being resolved, this can be due to 2 different reasons:

* The Asset is not published
* You need to add `include: N` to your request to Contentful, with N being the level of nesting in your resource, if you followed the Content Types as what the Template has, 2 would resolve it.

If you still find the error after checking these 2 things, please let me know.

Hope this helps

**Comment by whosdustin** [comment]
it still doesn't seem to be working. I am trying to query 1 entry, where your example only displays entries. This is what I am doing in the app.rb.

```
get '/:id' do
      erb :"show",
      locals: {
        product: contentful(
           ENV['CONTENTFUL_SPACE'],
           ENV['CONTENTFUL_TOKEN']
       ).entry(
         params[:id],
         include: 2
       )
    }
end
```

**Comment by whosdustin** [comment]
I think after a little bit of digging I found my issue. It's not pretty but I finally found out to query 1 entry through `).entries(` and loop through itself. I'm sure theres ways to make it cleaner, but I did make it work.

**app.rb**
```
get '/:id' do
      id = params[:id]
      erb :"shop/show",
      locals: {
        product: contentful(
          ENV['CONTENTFUL_SPACE'],
          ENV['CONTENTFUL_TOKEN']
        ).entries(
          content_type: "product",
          include: 2
        ).select { |product| product.id }
      }
    end
```

**show.erb**
```
<% product.each do |product| %>
  <h1><%= product.product_name %></h1>
  <p><%= product.description %></p>
  <span>$<%= product.price %></span>
  <% product.images.each do |image| %>
    <img src="<%= image.image_url %>" alt="<%= image.description %>" height="140">
  <% end %>
<% end %>
```

**Comment by whosdustin** [comment]
I finally figured it out. I needed to grab one entry through `) .entries (` and then loop through the single entry.

**app.rb**
``` ruby
    get '/:id' do
      erb :"shop/show",
      locals: {
        product: contentful(
          ENV['CONTENTFUL_SPACE'],
          ENV['CONTENTFUL_TOKEN']
        ).entries(
          'sys.id' => params[:id]
        )
      }
    end
```

**show.erb**
``` html
<% product.each do |product| %>
  <div class="img-thumbs">
    <% product.images.each do |image| %>
      <img id="<%= image.id %>" src="<%= image.image_url height: 150 %>" alt="<%= image.description %>" >
    <% end %>
  </div>
  <h1><%= product.product_name %></h1>
  <p><%= product.description %></p>
  <span>$<%= product.price %></span>
<% end %>
```

**Comment by dlitvakb** [comment]
Hey @whosdustin,

The `/entries/:id` endpoint (which the `#entry` method calls, doesn't resolve links as you already found out (this is described in the API docs [here](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/links/retrieval-of-linked-items/get-all-entries-of-a-space)). 

Therefore as you already resolved it, you have to query using `.entries('sys.id' => 'your_entry_id')`, to get the list response and be able to have the includes resolved.

Cheers

**Comment by whosdustin** [comment]
Thanks for the help. This is all new to me (reading and using API's). It takes me a little longer to know what I'm looking for than usual.
